# Dependencies
gems:
  - jekyll-sitemap
  - jekyll-assets
  - font-awesome-sass

# Site
title: Sorvetes Mila - Em breve estaremos no ar - Página em construção - Código5 WEB
description:
baseurl: ""
url: "http://www.sorvetesmila.com.br"
favicon: favicon.ico
exclude:
  - Gemfile*
  - bower.json
  - Guardfile
  - scripts


# Google Analytics
google_analytics: false

# Google Tag Manager
google_tagmanager: false

# Google site verification
google_site_verificatio: false

# Company
company:
  name: 'Sorvetes Mila'
  brand_img: 'logo_marca_mila_sorvetes.png'
  brand_img_alt: 'Sorvetes Mila - Logo'
  google_maps_url: 'https://www.google.com.br/maps/place/Av.+Gov.+J%C3%BAlio+Campos,+6237+-+Santa+Isabel,+V%C3%A1rzea+Grande+-+MT/@-15.6447619,-56.1801851,2617m/data=!3m1!1e3!4m5!3m4!1s0x939dad66ed33608d:0x94d037c55a2e566c!8m2!3d-15.6419451!4d-56.1766046?hl=pt-BR'
  address: 'Av. Julio Campos, 6237 - Varzea Grande-MT'
  phones:
    - icon: phone
      number: '(65) 3053-0337'
    - icon: phone
      number: '(65) 3053-3333'
  email: milasorvetes@hotmail.com
  link: "https://goo.gl/forms/KffgQwxVu5o5NwPJ3"
  linktexto: "Seja Um representante"

# Build
markdown: kramdown

# Sprockets
assets:
  prefix: "/assets"
  sources:
    - _assets/bower
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
  features:
    liquid: true
